#########################################################################################################
#########################################################################################################
#
# This script is for generating high-quality plots of various quantities generated by the other scripts
# Please refer to <arXiv link> for explaination of variables and instructions for using the code
#
#########################################################################################################
#########################################################################################################


import numpy as np
from scipy.interpolate import CubicSpline
import matplotlib.pyplot as plt
import matplotlib.patches as pch
from matplotlib import rcParams
from matplotlib import rc
from matplotlib.ticker import AutoMinorLocator



#########################################################################################################
# The plot settings are defined in this section
#
# It is recommended that you don't alter this section unless you're familiar with MatPlotLib and LaTeX
#########################################################################################################

def set_style():
    # activate LaTeX text rendering
    # plt.rc('text', usetex=True)

    #LaTex settings
    # plt.rcParams['text.latex.preamble']=r'\usepackage{amsmath} \boldmath'


    ###Plot settings:

    # dimensions of figure
    plt.rcParams['figure.figsize'] = (10, 7)

    # font
    plt.rcParams['axes.labelsize'] = plt.rcParams['font.size']
    plt.rcParams['axes.titlesize'] = 1.4*plt.rcParams['font.size']
    plt.rcParams['legend.fontsize'] = 1.4*plt.rcParams['font.size']
    plt.rcParams['xtick.labelsize'] = 1.4*plt.rcParams['font.size']
    plt.rcParams['ytick.labelsize'] = 1.4*plt.rcParams['font.size']

    # tick sizes
    plt.rcParams['xtick.major.size'] = 3
    plt.rcParams['xtick.minor.size'] = 3
    plt.rcParams['xtick.major.width'] = 1
    plt.rcParams['xtick.minor.width'] = 1
    plt.rcParams['ytick.major.size'] = 3
    plt.rcParams['ytick.minor.size'] = 3
    plt.rcParams['ytick.major.width'] = 1
    plt.rcParams['ytick.minor.width'] = 1

    #legends
    plt.rcParams['legend.frameon'] = True
    # width of axes
    plt.rcParams['axes.linewidth'] = 1

def plot_background_n_vs_t(T, N):
    plt.figure()
    plot1 = plt.plot(T, N)
    plt.setp(plot1, color='g', linewidth=4, linestyle='-')
    plt.text(420, 75, r'end of inflation', fontsize=20, color='purple')
    plt.axhline(y=np.max(N), ls='--', lw=1.5, color='k')
    plt.xlabel(r'$T$', fontsize=22)
    plt.ylabel(r'$N$', fontsize=24)
    plt.grid(which='major', color='lightgrey', linestyle='-', linewidth=1, zorder=0)
    plt.show()

def plot_eps_h(Ne, epsH, etaH=None):
    plt.figure()
    if etaH is not None:
        plot1 = plt.plot(Ne, np.abs(etaH))
        plt.setp(plot1, color='r', linewidth=3.5, linestyle='-', label=r'$|\eta_H|$')
    
    plot2 = plt.plot(Ne, epsH)
    plt.setp(plot2, color='g', linewidth=3.5, linestyle='-', label=r'$\epsilon_H$')

    plt.axhline(y=1, ls='--', color='k', lw=2)
    plt.yscale('log')
    plt.xlabel(r"$N_e$", fontsize=22)
    plt.ylabel(r"$\epsilon_H$", fontsize=24)
    plt.legend()
    plt.grid(which='major', color='lightgrey', linestyle='-', linewidth=1, zorder=0)
    plt.show()

def plot_phase_space(phi, phi_dot):
    plt.figure()
    plot1 = plt.plot(phi, phi_dot)
    plt.setp(plot1, color='g', linewidth=4, linestyle='-')
    plt.axvline(x=0.615, ls='--', lw=2, color='k')
    plt.text(0.7, -3e-6, r'end of inflation', fontsize=20, color='purple', rotation=90)
    plt.xlabel(r'$\phi/m_p$', fontsize = 22) 
    plt.ylabel(r'$\dot\phi/m_p^2$', fontsize = 24)
    plt.grid(which='major', color='lightgrey', linestyle='-', linewidth=1, zorder=0)
    plt.show()

def plot_power_spectrum(Ne, Ps, Pt):
    plt.figure()
    plt.plot(Ne, Ps, 'g-', lw=4, label='Scalar (slow-roll)')
    plt.plot(Ne, Pt, 'r-', lw=4, label='Tensor (slow-roll)')
    plt.yscale('log')
    plt.xlim(5, 70)
    plt.ylim(1e-12, 1e-8)
    plt.xlabel(r"$N_e$", fontsize=22)
    plt.ylabel(r"Power", fontsize=24)
    plt.title(r"Scalar & Tensor Power Spectra", fontsize=22)
    plt.legend(frameon=True, fontsize=14, borderpad=1.2)
    plt.grid(which='major', color='lightgrey', linestyle='-', linewidth=1, zorder=0)
    plt.show()



# Model definitions are now in inflation_models.py



#########################################################################################################
# This is the main section of the code and follows a menu-driven format
#
# The section is divided into segments, each concerning different parts of inflationary dynamics
# Each segment is further divided into subsegments that contain different plots
# Select the segment corresponding to the dynamics you want to study (see the menu below) and uncomment
#	the subsegment corresponding to the required plot
# In each subsegment, there are labels, lines, arrows and other markers to accompany the main plots. 
#   It is recommended that you comment those out and include them at suitable locations in your plots. 
#########################################################################################################

if __name__ == "__main__":
    set_style()
    print("This module provides plotting utilities. Import functions to use.")
    # Legacy menu code removed to prevent errors with missing data files.
